"use client";

import { motion, AnimatePresence } from "framer-motion";
import { X, Check } from "lucide-react";

interface UpgradeModalProps {
    isOpen: boolean;
    onClose: () => void;
}

export function UpgradeModal({ isOpen, onClose }: UpgradeModalProps) {
    return (
        <AnimatePresence>
            {isOpen && (
                <div className="fixed inset-0 z-[100] flex items-center justify-center px-4">
                    {/* Backdrop */}
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        onClick={onClose}
                        className="absolute inset-0 bg-black/80 backdrop-blur-sm"
                    />

                    {/* Modal */}
                    <motion.div
                        initial={{ scale: 0.95, opacity: 0, y: 20 }}
                        animate={{ scale: 1, opacity: 1, y: 0 }}
                        exit={{ scale: 0.95, opacity: 0, y: 20 }}
                        className="relative w-full max-w-lg bg-zinc-950 border border-zinc-800 rounded-2xl overflow-hidden shadow-2xl"
                    >
                        {/* Gradient Header */}
                        <div className="h-32 bg-gradient-to-br from-lime-400/20 to-transparent flex items-center justify-center relative">
                            <div className="absolute inset-0 bg-[url('/noise.svg')] opacity-30" />
                            <h2 className="text-3xl font-bold text-white font-syne relative z-10 tracking-tight">
                                GITFLEX <span className="text-lime-400">PRO</span>
                            </h2>
                        </div>

                        <button
                            onClick={onClose}
                            className="absolute top-6 right-6 text-zinc-500 hover:text-white transition-colors z-20"
                        >
                            <X size={24} />
                        </button>

                        <div className="p-8">
                            <p className="text-zinc-400 text-center mb-8">
                                Unlock your full creative potential. One-time payment, lifetime access.
                            </p>

                            <ul className="space-y-4 mb-8">
                                {[
                                    "Access all 10+ Premium Variants",
                                    "Remove 'Generated by GitFlex' Badge",
                                    "Unlimited Regenerations",
                                    "Project Readme Generator (Coming Soon)"
                                ].map((feature, i) => (
                                    <li key={i} className="flex items-center gap-3 text-zinc-300">
                                        <div className="p-1 rounded-full bg-lime-400/10 text-lime-400">
                                            <Check size={14} />
                                        </div>
                                        {feature}
                                    </li>
                                ))}
                            </ul>

                            <button className="w-full py-4 rounded-lg bg-lime-400 text-black font-bold font-mono uppercase hover:bg-white transition-colors text-lg tracking-wide mb-4">
                                Upgrade for $9
                            </button>

                            <p className="text-center text-xs text-zinc-600 uppercase tracking-widest cursor-pointer hover:text-zinc-400" onClick={onClose}>
                                Maybe Later
                            </p>
                        </div>
                    </motion.div>
                </div>
            )}
        </AnimatePresence>
    );
}
