import { IntelligenceReport, VisualTheme, FeaturedProject } from "./intelligence";

export interface ReadmeVariant {
    id: string;
    name: string;
    markdown: string;
    theme: VisualTheme;
    isPremium?: boolean;
}

/**
 * UTILS FOR PREMIUM GENERATION
 */

const getShield = (label: string, value: string, color: string = "lime") =>
    `![${label}](https://img.shields.io/badge/${encodeURIComponent(label)}-${encodeURIComponent(value)}-${color}?style=flat-square&labelColor=18181b)`;

const formatProjects = (projects: FeaturedProject[], style: 'classic' | 'minimal' | 'cards') => {
    if (style === 'minimal') {
        return projects.map(p => `- **[${p.name}](${p.url})** — ${p.description}`).join('\n');
    }
    if (style === 'cards') {
        return projects.map(p => `
### [${p.name}](${p.url})
> ${p.description}
${getShield("Stars", p.stars.toString(), "white")} ${getShield("Stack", p.language, "zinc")}
`).join('\n');
    }
    return projects.map(p => `#### ${p.name}\n${p.description}\n`).join('\n');
};

const getPersonalityBio = (role: string) => {
    const bios: Record<string, string> = {
        "Backend Architect": "Focused on building resilient distributed systems and optimizing high-throughput data pipelines. I prefer clean abstractions over clever hacks.",
        "Frontend Engineer": "Obsessed with interaction design and accessible interfaces. I believe the best UI is the one that feels invisible to the user.",
        "Creative Technologist": "Exploring the tension between code and canvas. I build immersive experiences that push the boundaries of what's possible in the browser.",
        "ML Engineer": "Deeply invested in making intelligence practical. My focus is on robust model deployment and data hygiene.",
        "Indie Hacker": "Generalist by choice, builder by nature. I focus on shipping MVPs that solve real problems with zero technical debt.",
        "Full Stack Dev": "End-to-end builder with a passion for architectural integrity from database schema to UI components.",
        "Systems Designer": "Operating at the intersection of hardware and high-level abstractions. Zero-cost abstractions are my love language.",
        "UI Scientist": "Experimental builder focusing on the evolution of human-computer interaction. Prototypes are my primary medium."
    };
    return bios[role] || "Passionate developer focused on building meaningful software and contributing to the open-source community.";
};

/**
 * VARIANTS
 */

export function generateVariants(report: IntelligenceReport): ReadmeVariant[] {
    const { primary, secondary, stackStrength, featuredProjects } = report;
    const role = primary.role;

    const topLangs = Object.entries(stackStrength)
        .sort(([, a], [, b]) => b - a)
        .slice(0, 5)
        .map(([name]) => name);

    const variants: ReadmeVariant[] = [];

    // 1. MINIMAL & CLEAN (The "Architect" / "Minimalist" hybrid)
    variants.push({
        id: "minimal",
        name: "Minimal & Clean",
        theme: "Minimalist",
        isPremium: false,
        markdown: `
# ${role.toLowerCase()}.

${getPersonalityBio(role)}

### ⚡ Technical Focus
${topLangs.join(' • ')}

### 🏗 Featured Work
${formatProjects(featuredProjects, 'minimal')}

---
*Generated by GitFlex Intelligence — Synthesis of ${report.primary.confidence}% accuracy.*
`.trim()
    });

    // 2. BOLD & EXPRESSIVE (The "Artist" Style)
    variants.push({
        id: "bold",
        name: "Bold & Expressive",
        theme: "Artist",
        isPremium: true,
        markdown: `
<div align="center">
  <h1>✦ ${role.toUpperCase()} ✦</h1>
  <p align="center">
    <strong>Design-driven engineering. Performance-first architecture.</strong>
  </p>
  <br/>
</div>

### ✦ ABOUT
${getPersonalityBio(role)} ${secondary ? `Hybrid background in ${secondary.role}.` : ''}

### ✦ ECOSYSTEM
${topLangs.map(l => getShield(l, "Expertise", "lime")).join(' ')}

### ✦ RECENT ARCHITECTURES
${formatProjects(featuredProjects, 'cards')}

<br/>

<div align="center">
  <img src="https://github-readme-stats.vercel.app/api/top-langs/?username=user&layout=compact&theme=dark" alt="Top Langs" />
</div>
`.trim()
    });

    // 3. RECRUITER-FOCUSED (The "Professional" Style)
    variants.push({
        id: "pro",
        name: "Recruiter Focused",
        theme: "Architect",
        isPremium: true,
        markdown: `
# ${role}
**Proven Expertise in ${topLangs[0]} ecosystem and ${report.primary.theme} methodologies.**

### 💼 Professional Overview
${getPersonalityBio(role)}

- 🔭 **Current Focus**: ${report.signals[0]?.title || 'Professional Development'}
- 🌱 **Recent Growth**: Detected emerging strength in ${report.emerging?.title.replace('Emerging: ', '') || 'New Frameworks'}
- ⚡ **Signal Strength**: ${report.primary.confidence}% match for ${role} patterns.

### 🛠 Core Competencies
| Category | Stack | Confidence |
| :--- | :--- | :--- |
| Primary | ${topLangs.slice(0, 2).join(', ')} | High |
| Supporting | ${topLangs.slice(2, 4).join(', ')} | Mid-Market |

### 🚀 Key Open Source Contributions
${formatProjects(featuredProjects, 'classic')}

### 📫 Let's Connect
- LinkedIn: [Your Profile](#)
- Portfolio: [YourSite.com](#)
`.trim()
    });

    // 4. THE TERMINAL (Developer-to-Developer)
    variants.push({
        id: "terminal",
        name: "Terminal Interface",
        theme: "Architect",
        isPremium: false,
        markdown: `
\`\`\`bash
$ whoami
> ${role}

$ gitflex-analysis --report
{
  "confidence": "${report.primary.confidence}%",
  "status": "Online",
  "philosophy": "Building elegant solutions to complex problems."
}

$ ls projects/
${featuredProjects.map(p => `+ ${p.name}/`).join('\n')}

$ cat skills.txt
[ ${topLangs.join(', ')} ]

$ tail -n 1 thoughts.log
> Refined the gap between code and design.
\`\`\`
`.trim()
    });

    return variants;
}
